var paymentController = require('../controllers/paymentControllers.js')
var router = require('express').Router()

//how many payments have been generated by a debtor
router.get('/debtor/:id', (req,res) =>{
    paymentController.totalAndAmountByDebtor(req,res);
})

// owner will know how many payments and how much out of the total it is
router.get('/owner/:id', (req,res) =>{
    paymentController.totalAndAmountByOwner(req,res);
})

// owner will know how many payments and how much out of the total it is by date
router.get('/owner/:id', (req,res) =>{
    paymentController.totalAndAmountByOwnerByDate(req,res);
})

//most recent payment by date for an specific owner 
router.get('/owner/:id', (req,res) =>{
    paymentController.mostRecentByOwner(req,res);
})

//how many payments have been realized out of all the owners
router.get('/', (req,res) =>{
    paymentController.list(req,res);
})

//payments considered by owner and date
router.get('/owner/:id', (req,res) =>{
    paymentController.listByDate(req,res);
})

// how many and total amount of payments received by an owner
router.get('/owner/:id', (req,res) =>{
    ownerController.totalAssociatedPayments(req,res);
})

//how many payments and how much out of them has a debtor realised in a certain date
router.get('/debtor/:id', (req,res) =>{
    paymentController.totalAndAmountByDebtorByDate(req,res);
})


